services:
  postgres:
    image: postgres:16
    container_name: postgres_db_gda
    restart: always
    environment:
      POSTGRES_USER: apiUser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appdb_gda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_gda:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gda
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data_gda:
